/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IWcTabContentData,
  IWcTabHeaderData,
} from './utils/model';


export namespace Components {

  interface WcTabsContent {
    'getChild': () => Promise<IWcTabContentData>;
    'name': string;
  }
  interface WcTabsContentAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface WcTabsHeader {
    'disabled': boolean;
    'getChild': () => Promise<IWcTabHeaderData>;
    'name': string;
  }
  interface WcTabsHeaderAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'name'?: string;
    'onOnSelect'?: (event: CustomEvent) => void;
  }

  interface WcTabs {
    'selection': number;
  }
  interface WcTabsAttributes extends StencilHTMLAttributes {
    'selection'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcTabsContent': Components.WcTabsContent;
    'WcTabsHeader': Components.WcTabsHeader;
    'WcTabs': Components.WcTabs;
  }

  interface StencilIntrinsicElements {
    'wc-tabs-content': Components.WcTabsContentAttributes;
    'wc-tabs-header': Components.WcTabsHeaderAttributes;
    'wc-tabs': Components.WcTabsAttributes;
  }


  interface HTMLWcTabsContentElement extends Components.WcTabsContent, HTMLStencilElement {}
  var HTMLWcTabsContentElement: {
    prototype: HTMLWcTabsContentElement;
    new (): HTMLWcTabsContentElement;
  };

  interface HTMLWcTabsHeaderElement extends Components.WcTabsHeader, HTMLStencilElement {}
  var HTMLWcTabsHeaderElement: {
    prototype: HTMLWcTabsHeaderElement;
    new (): HTMLWcTabsHeaderElement;
  };

  interface HTMLWcTabsElement extends Components.WcTabs, HTMLStencilElement {}
  var HTMLWcTabsElement: {
    prototype: HTMLWcTabsElement;
    new (): HTMLWcTabsElement;
  };

  interface HTMLElementTagNameMap {
    'wc-tabs-content': HTMLWcTabsContentElement
    'wc-tabs-header': HTMLWcTabsHeaderElement
    'wc-tabs': HTMLWcTabsElement
  }

  interface ElementTagNameMap {
    'wc-tabs-content': HTMLWcTabsContentElement;
    'wc-tabs-header': HTMLWcTabsHeaderElement;
    'wc-tabs': HTMLWcTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
